FROM golang:1.13 AS builder
WORKDIR /go/src/github.com/openshift/sriov-network-operator
COPY . .
RUN make _build-sriov-network-config-daemon BIN_PATH=build/_output/cmd
RUN make plugins BIN_PATH=build/_output/pkg

FROM centos:7
RUN yum -y update && yum -y install hwdata git make automake autoconf libtool gcc zlib-devel infiniband-diags-devel gcc-c++ openssl-devel && yum clean all
RUN git clone https://github.com/Mellanox/mstflint.git && cd mstflint && ./autogen.sh && ./configure && make && make install

LABEL io.k8s.display-name="sriov-network-config-daemon" \
      io.k8s.description="This is a daemon that manage and config sriov network devices in Kubernetes cluster"
COPY --from=builder /go/src/github.com/openshift/sriov-network-operator/build/_output/cmd/sriov-network-config-daemon /usr/bin/
COPY --from=builder /go/src/github.com/openshift/sriov-network-operator/build/_output/pkg/plugins /plugins
COPY bindata /bindata
ENV PLUGINSPATH=/plugins
CMD ["/usr/bin/sriov-network-config-daemon"]
