apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{.SriovNetworkName}}
  namespace: {{.SriovNetworkNamespace}}
  annotations:
    k8s.v1.cni.cncf.io/resourceName: {{.SriovCniResourceName}}
spec:
  config: |
    {"cniVersion":"0.3.1","name":"sriov-net","type":"sriov",{{if .SpoofChkConfigured}} "spoofchk":"{{.SriovCniSpoofChk}}", {{- end}} {{if .TrustConfigured}} "trust":"{{.SriovCniTrust}}", {{- end}} "vlan":{{.SriovCniVlan}},{{.SriovCniIpam}}}
